### PR TITLE
fixes dependency on expired snmplabs.com domain

### PR DESCRIPTION
**Pull request by chrisns**
greater narrative in #1

### CODE REVIEW

**Comment by chrisns** [comment]
could use https://github.com/DataDog/integrations-core/pull/9952/files#diff-cf0942922248f35877e82fe18594f8245b5524121917b4683f2c3781d83a0dc1R95 instead if preferred

**Comment by mtdcr** [comment]
Thank you very much!

**Comment by chrisns** [comment]
> Thank you very much!

Please could you bump the version?
Thanks

**Comment by mtdcr** [comment]
Done and uploaded to pypi.org.

**Pull request merged**
